name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install ninja and g++
        run: sudo apt install ninja-build g++-8
      - name: Install Conan
        run: pip install conan==1.21.0
      - name: Install source files
        run: |
          mkdir build && cd build
          conan workspace install ..
          cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=install/mgs -DBUILD_TESTING=OFF
          ninja install
      - uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/install
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
